name: 'action runner switch'
description: 'switching runners if the included minutes are consumed'
branding:
  icon: dollar-sign
  color: blue

inputs:
  token:
    description: token to request billing information (needs organization admin read permissions)
    required: true
  runner:
    description: github runner to be used
    required: false
    default: ubuntu-latest
  alternative_runner:
    description: runner used after included github minutes have been consumed
    required: false
    default: ubuntu-latest

outputs:
  runner:
    description: runner to be used based on the consumed minutes
    value: ${{ steps.runner.outputs.runner }}

runs:
  using: "composite"
  steps:
    - name: check if organization
      if: ${{ ! github.event.organization.login }}
      shell: bash
      run: |
        echo "this only works for organizations"
        exit 1
    - name: login to github
      shell: bash
      run: echo ${{ inputs.token }} | gh auth login --with-token
    - name: get info
      id: info
      shell: bash
      run: |
        PAYLOAD=$(gh api "/orgs/${{ github.event.organization.login }}/settings/billing/usage?year=$(date +%Y)&month=$(date +%m)")
        echo "net_amount=$(echo $PAYLOAD | jq '[.usageItems[] | select( .product == "actions" ) | select( .unitType == "Minutes" ) | .netAmount] | add')" >>$GITHUB_OUTPUT
    - name: determine runner
      id: runner
      shell: bash
      run: |
        if [ "${{ steps.info.outputs.net_amount }}" -gt "0" ]; then
          echo "runner=${{ inputs.alternative_runner }}" >>$GITHUB_OUTPUT
        else
          echo "runner=${{ inputs.runner }}" >>$GITHUB_OUTPUT
        fi
